# deploy.toml app configuration file generated for build on 2023-06-18T14:20:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "ams"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
